name: doodoo-fam
services:
  - name: api
    source_dir: /doodoo
    github:
      repo: jiaenkoh45/nxMonorepo
      branch: master
      deploy_on_push: true
    build_command: npm install && npx playwright install chromium && npm run build
    run_command: node dist/src/main.js
    environment_slug: node-js
    instance_size_slug: apps-s-1vcpu-0.5gb
    http_port: 8080
    routes:
      - path: /api
    envs:
      - key: PORT
        value: "8080"
        scope: RUN_AND_BUILD_TIME
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: CORS_ORIGIN
        scope: RUN_TIME
        value: ${web.PUBLIC_URL}
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /workspace/doodoo/.cache/ms-playwright
        scope: RUN_AND_BUILD_TIME

  - name: web
    source_dir: /
    github:
      repo: jiaenkoh45/nxMonorepo
      branch: master
      deploy_on_push: true
    build_command: npm install && npm run build:prod
    run_command: node dist/doodoo-fam/server/server.mjs
    environment_slug: node-js
    instance_size_slug: apps-s-1vcpu-0.5gb
    http_port: 8080
    routes:
      - path: /
    envs:
      - key: PORT
        value: "8080"
        scope: RUN_AND_BUILD_TIME
